apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: {{.namespace}}
  labels:
    app: webapp
    component: service
spec:
  ports:
    - name: http-port #important to name for istio
      port: 8083
  selector:
    app: webapp
